version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${ecr_domain}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export DATE_TAG=$(date +%Y.%m.%d-%H.%M.%S)
      - docker image tag ${image_repo_name}:latest ${ecr_domain}/${image_repo_name}:$DATE_TAG
      - docker image tag ${image_repo_name}:latest ${ecr_domain}/${image_repo_name}:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${ecr_domain}/${image_repo_name}:$DATE_TAG
      - docker push ${ecr_domain}/${image_repo_name}:latest
